python testGetGrammar.py "What is Python?"
python testGetGrammar.py "What is the Python Software Foundation?"
python testGetGrammar.py "Are there copyright restrictions on the use of Python?"
python testGetGrammar.py "Why was Python created in the first place?"
python testGetGrammar.py "What is Python good for?"
python testGetGrammar.py "How does the Python version numbering scheme work?"
python testGetGrammar.py "How do I obtain a copy of the Python source?"
python testGetGrammar.py "How do I get documentation on Python?"
python testGetGrammar.py "I've never programmed before. Is there a Python tutorial?"
python testGetGrammar.py "Is there a newsgroup or mailing list devoted to Python?"
python testGetGrammar.py "How do I get a beta test version of Python?"
python testGetGrammar.py "How do I submit bug reports and patches for Python?"
python testGetGrammar.py "Are there any published articles about Python that I can reference?"
python testGetGrammar.py "Are there any books on Python?"
python testGetGrammar.py "Where in the world is www.python.org located?"
python testGetGrammar.py "Why is it called Python?"
python testGetGrammar.py "Do I have to like Monty Python's Flying Circus??"
